### ISSUE TITLE
Provision for Shake Sample Fails with `stderr maxBuffer exceeded` on Windows

### ISSUE THREAD

**Issue by cicorias** [Microsoft/azure-iot-developer-kit#189]
During task deploy, errors occur indicating some sort of stderr, however, maxBuffer error is shown, and nothing about what the error is.

To Repro:

Windows 1709 Pro (Fall Creators Update)

1. run latest (devkit_install_win_1.2.0.29.zip) dev kit install.
2. Firmware on board is 1.2.0
3. Open Visual Studio Code & Plugin Card
4. Choose the ShakeShake Project.
5. Run the provision task

During provision task - finally see the below, and then it just is stuck.

```
Executing task: node "C:\Users\cicorias\azure-board-cli\out\cli.js" provision .bin <

  - checking pre-conditions of task: node.js version
  V node.js version: v7.2.1
  - checking pre-conditions of task: azure cli version
  V azure cli version: 2.0.21
  - checking pre-conditions of task: subscription
? What subscription would you like to choose? CSE NYC Tyrell Team Subscription (b00a4572-2115-4d17-a2e5-b83326ab371b) (scicoria@microsoft.com)
  V subscription: b00a4572-2115-4d17-a2e5-b83326ab371b
  - checking pre-conditions of task: azure cli iothub
? Which Resource Group would you like to choose? Create new...
? Resource Group Name:  shawniottesting
Creating resource group [shawniottesting-group-acd0] ...
Create resource group [shawniottesting-group-acd0] Succeeded.
? IoT Hub Name:  cicorias
  V azure cli iothub: {"iotHubName":"cicorias-iothub-acd0","subscription":"b00a4572-2115-4d17-a2e5-b83326ab371b","resourceGroup":"shawniottesting-group-acd0"}
  - checking pre-conditions of task: function app
  V function app: function app name: cicorias-iothub-acd0-shakea3c0
  - checking pre-conditions of task: ARM template deployment
-   X ARM template deployment: Unexpected error when executing "C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\wbin\\az.cmd" group deployment create --resource-group shawniottesting-group-acd0 --template-file ".bin\azuredeploy.json" --parameters "{\"iotHubName\":{\"value\":\"cicorias-iothub-acd0\"},\"iotHubSku\":{\"value\":\"F1\"},\"iotHubCapacity\":{\"value\":1},\"iotHubExisted\":{\"value\":\"\"},\"functionAppName\":{\"value\":\"cicorias-iothub-acd0-shakea3c0\"}}" : stderr maxBuffer exceeded. Error: stderr maxBuffer exceeded
    at Socket.onChildStderr (child_process.js:283:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
(node:26264) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Unexpected error when executing "C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\wbin\\az.cmd" group deployment create --resource-group shawniottesting-group-acd0 --template-file ".bin\azuredeploy.json" --parameters "{\"iotHubName\":{\"value\":\"cicorias-iothub-acd0\"},\"iotHubSku\":{\"value\":\"F1\"},\"iotHubCapacity\":{\"value\":1},\"iotHubExisted\":{\"value\":\"\"},\"functionAppName\":{\"value\":\"cicorias-iothub-acd0-shakea3c0\"}}" : stderr maxBuffer exceeded. Error: stderr maxBuffer exceeded
    at Socket.onChildStderr (child_process.js:283:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
(node:26264) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
|
```
![image](https://user-images.githubusercontent.com/1080406/33098068-1c5561c2-ceda-11e7-9ed3-90be2d92b81a.png)

**Comment by Sneezry** [comment]
It seems ARM deployment failed on Azure side. Could you please check deployment log detail?

To find deployment log, do as following:

![snipaste_2017-11-22_11-00-27](https://user-images.githubusercontent.com/1621293/33107906-622027b0-cf74-11e7-80b3-68b2e1135336.png)

**Comment by cicorias** [comment]
The deployment during storage account provision had three retries but eventually all succeeded. In the end, the deployment was 100% pass.

I suspect during the retries errors collected and blew out the stderr buffer.

Since then no further failures.

You can close as its working now, but it is choking in this situation. Azure status had some storage issues today on creation intermittent failures.

**Comment by Sneezry** [comment]
Thanks for your feedback. Then I will close this issue. Please feel free to open a new issue if you have any other questions.
